export const SET_LOGIN = 'SET_LOGIN';
export const SET_ID = 'SET_ID';

export const SET_LOGIN_SELLER = 'SET_LOGIN_SELLER';
export const SET_ID_SELLER = 'SET_ID_SELLER';

export const SET_DASHBOARD = 'SET_DASHBOARD';

export const SET_PRODUCTS = 'SET_PRODUCTS';

export const SET_SEARCH = 'SET_SEARCH';

export const SET_PRODRESULTS = 'SET_PRODRESULTS'

export const SET_BROWSED_PROD = 'SET_BROWSED_PROD'
export const SET_VARIETY = 'SET_VARIETY'

export const SET_COMMENTS = 'SET_COMMENTS';

export const SET_USER_CREDS = 'SET_USER_CREDS';

export const SET_ADDRESSES = 'SET_ADDRESSES';
export const SET_ADDRESSES_VIEW = 'SET_ADDRESSES_VIEW';

export const SET_CART = 'SET_CART';
export const SET_PENDING = 'SET_PENDING';
export const SET_ON_DELIVERY = 'SET_ON_DELIVERY';
export const SET_RECEIVED = 'SET_RECEIVED';
export const SET_CANCELLED = 'SET_CANCELLED';

export const SET_SHOP_RESULT = 'SET_SHOP_RESULT';

export const SET_SELLER_INFO = 'SET_SELLER_INFO';

export const SET_ORDERS_ADMIN = 'SET_ORDERS_ADMIN'; //PENDING Unconfirmed
export const SET_ORDERS_PREPARING = 'SET_ORDERS_PREPARING';
export const SET_ORDERS_WAITING = 'SET_ORDERS_WAITING';
export const SET_ORDERS_ONDELIVERY = 'SET_ORDERS_ONDELIVERY';
export const SET_ORDERS_DELIVERED = 'SET_ORDERS_DELIVERED';
export const SET_ORDERS_CANCELLED = 'SET_ORDERS_CANCELLED';

export const TOGGLE_CHAT_BOX = 'TOGGLE_CHAT_BOX';

export const MINIMIZE_CHAT_BOX = 'MINIMIZE_CHAT_BOX';

export const SHOP_PREVIEW = 'SHOP_PREVIEW';

export const USER_MESSAGE_LIST = 'USER_MESSAGE_LIST';
export const USER_MESSAGE_INBOX = 'USER_MESSAGE_INBOX';

export const SELLER_MESSAGE_LIST = 'SELLER_MESSAGE_LIST';
export const SELLER_MESSAGE_INBOX = 'SELLER_MESSAGE_INBOX';

export const GET_PAYMENT_ACCOUNTS = 'GET_PAYMENT_ACCOUNTS';
export const SET_SHOP_ADDRESS = 'SET_SHOP_ADDRESS';
export const SET_SHOP_NUMBER = 'SET_SHOP_NUMBER';

export const SET_VERTWO_STATUS = 'SET_VERTWO_STATUS';

export const CHAT_SUPPORT_LIST = 'CHAT_SUPPORT_LIST';

export const SET_ORDER_VIEW = 'SET_ORDER_VIEW';

export const SET_SAVED_CONTACTS = 'SET_SAVED_CONTACTS';

export const SET_PRBR_SHOP = 'SET_PRBR_SHOP';
export const SET_SHOP_PR = 'SET_SHOP_PR';

export const SET_PRODUCT_DETAILS_ADMIN = 'SET_PRODUCT_DETAILS_ADMIN';
